version: "3"
services:
  wikidata-wikifier:
    image: wikidata-wikifier
    container_name: wikidata-wikifier
    command: sh -c 'python3 wikifier_service.py'
    restart: always
    ports:
      - "1703:1703"
    environment:
      - WIKIFIER_ES_URL=http://localhost:9200
      - WIKIFIER_ES_INDEX=wikidatadwd-augmented
      - WIKIFIER_MODEL_PATH=/api/wikifier/model/epoch_17_loss_0.014523069374263287_top1_0.9675043327556326.pth
      - WIKIFIER_MIN_MAX_SCALER_PATH=/api/wikifier/model/tl_pipeline_normalization_factor.pkl
      - PSEUDO_GT_MODEL=/api/wikifier/model/epoch_1_loss_0.534353494644165_top1_0.7883487007544007.pth
      - PSEUDO_GT_MIN_MAX_SCALER_PATH=/api/wikifier/model/normalization_factor.pkl
